### ISSUE TITLE
Remove section explanations on copy/paste page

### ISSUE THREAD

**Issue by jjeff** [Lullabot/fivefifteen#57] opened 2015-01-27 17:28 UTC
I often have the screen reader speak 5:15s to me. However, I end up hearing the section explanations over and over again. When reading visually, it's easy enough to skip over these. But the truth is that even visually, they're unnecessary and they clutter things up.

It would be easy enough to add a checkbox labeled "hide section explanations", but I would argue even that is unnecessary. Most managers are going to understand what each section is – heck they've probably *written* the explanations *themselves*.

**Comment by q0rban** [comment] 2015-01-27 17:41
Duplicate of #53 and #15.

**Closed by q0rban** 2015-01-27 17:41 UTC
