### ISSUE TITLE
Exclude guidelines from preview text?

### ISSUE THREAD

**Issue by DannyJoris** [Lullabot/fivefifteen#53] opened 2014-08-24 21:42 UTC
Should the guidelines be left out the preview text? I'm not on the receiving end of these emails, but I would think the guidelines would be distracting, while the section title followed with the user input would suffice?

**Comment by q0rban** [comment] 2015-01-27 17:42
History in #15.

**Comment by q0rban** [comment] 2015-01-27 17:42
I marked #57 as a duplicate of this.

**Closed** 2023-09-25 23:24 UTC
